version: '3.7'
services:
  redis:
    image: redis:alpine
    container_name: concert-redis
    command: redis-server --port 6379
    hostname: redis
    ports:
      - 56379:6379
  mysql:
    cap_add:
      - SYS_NICE
    container_name: concert-mysql
    image: ubuntu/mysql:edge
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp=1
    ports:
      - 53306:3306
    environment:
      - MYSQL_DATABASE=lecture
      - MYSQL_USER=abcd
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d